typedef enum {
    STATE_IDLE,
    STATE_WALK,
    STATE_CROUCH,
    STATE_JUMP,
    STATE_LIGHT_PUNCH,
    STATE_HEAVY_PUNCH,
    STATE_BLOCK_STAND,
    STATE_BLOCK_CROUCH,
    STATE_LOW_PUNCH,
    STATE_SKILL1,
    STATE_SKILL2,
    STATE_SKILL3,
    STATE_ULTIMATE
} CharacterState;