typedef enum {
    STATE_IDLE,
    STATE_WALK,
    STATE_CROUCH,
    STATE_CROUCHING,
    STATE_JUMP,
    STATE_LIGHT_PUNCH,
    STATE_HEAVY_PUNCH,
    STATE_BLOCK_STAND,
    STATE_BLOCK_CROUCH,
    STATE_BLOCK_RELEASE,
    STATE_LOW_LIGHT_PUNCH, // Already exists
    STATE_LOW_HEAVY_PUNCH,
    STATE_DAMAGED,
    STATE_FALL,
    STATE_SKILL1,
    STATE_SKILL2,
    STATE_SKILL3,
    STATE_ULTIMATE
} CharacterState;